DELETE http://localhost:3000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMWY1M2Y3MC0zM2E4LTQ1ZDMtOTIyMy1lODdkZmYyYTNlM2QiLCJlbWFpbCI6ImFobWVkYWxsb3VzaGdwdDJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzQ1MDU3OTg0LCJleHAiOjE3NDUwNjE1ODQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.cngMRzZeA6AmXWvuCZ3LFNnRMVs2uwDES2MeWSyHVPM
