PATCH http://localhost:3000/user/change-role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMWY1M2Y3MC0zM2E4LTQ1ZDMtOTIyMy1lODdkZmYyYTNlM2QiLCJlbWFpbCI6ImFobWVkYWxsb3VzaGdwdDJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzQ1MjI5MDE5LCJleHAiOjE3NDUyMzI2MTksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.aWLq5y_V59CxNf498QRvLn8o-YgZwnakMktXayPm-I8
